name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.2.3
  - pytest=6.2.2
  - scipy=1.6.1
  - pip=20.3.3
  - pip:
      - protobuf==3.20.0
      - mlflow==2.8.1
      - wandb==0.10.21
